# Generated by Django 3.1.3 on 2021-09-09 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Believer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('church', 'from Church'), ('online', 'from Online')], max_length=10)),
                ('category', models.CharField(choices=[('low', 'Lower'), ('normal', 'Normal level'), ('hero', 'Hero Level'), ('high', 'High Level')], max_length=10)),
                ('witness', models.CharField(blank=True, max_length=255, null=True)),
                ('witness_number', models.CharField(blank=True, max_length=255, null=True)),
                ('allowed', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='testimonies/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='testimonies/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('believer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to='testimony.believer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'testimonies',
            },
        ),
        migrations.AddField(
            model_name='believer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to='testimony.location'),
        ),
    ]
