# Generated by Django 3.1.3 on 2021-09-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimony', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
